# MIndNotes/k8s/06-filebeat-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: mindnotes
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log 
      enabled: true
      paths:
        - /var/log/containers/*.log 
      # Forcing it to read from the beginning of files for this test
      # This can cause duplicate logs if run multiple times on existing files, but good for diagnosing if it reads ANYTHING
      tail_files: false 
      scan_frequency: 5s # Check for new files more often

    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          node: ${NODE_NAME} 

    output.elasticsearch:
      hosts: ["http://elasticsearch-service.elk.svc.cluster.local:9200"]
      index: "filebeat-simplest-test-%{+yyyy.MM.dd}" # NEW, DISTINCT INDEX NAME
