# MIndNotes/k8s/06-filebeat-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: mindnotes # IMPORTANT: Namespace of your applications
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log # Using the basic 'log' input type, not 'container' for now
      enabled: true
      paths:
        - /var/log/containers/*.log # Broadly try to pick up all .log files in this dir
      # Optional: Add a field to know these are from the simple input
      # fields:
      #   input_type: simple_log_input
      # fields_under_root: true

    # Keep processors if you want metadata, though it might be less accurate without specific container context
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          node: ${NODE_NAME} 
          # Default indexers and matchers are generally okay
          # You might see warnings if it can't associate specific metadata without container ID context

    output.elasticsearch:
      hosts: ["http://elasticsearch-service.elk.svc.cluster.local:9200"] # VERIFY THIS FQDN
      index: "filebeat-simple-input-%{+yyyy.MM.dd}" # Use a DIFFERENT index name for this test
