apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: elk 
  labels:
    app: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: http
    name: http
  selector:
    app: elasticsearch
  type: ClusterIP
