apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: elk 
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: http
  selector:
    app: kibana
  type: NodePort # Or LoadBalancer, or use Ingress
  # If NodePort:
  # ports:
  # - port: 5601
  #   targetPort: 5601
  #   nodePort: 30001 # Example NodePort
