apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: mindnotes # IMPORTANT: Namespace of your applications
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_kubernetes_metadata:
          in_cluster: true # Use in-cluster discovery

    output.elasticsearch:
      hosts: ["http://elasticsearch-service.elk.svc.cluster.local:9200"] # Adjust if ES is in a different namespace
      # index: "mindnotes-logs-%{[agent.version]}-%{+yyyy.MM.dd}" # Optional custom index name
